-- Nesty Radar: acquisizione annunci + alert
create table if not exists listing_sources (
  id bigint generated by default as identity primary key,
  source_key text unique not null,
  source_name text not null,
  source_type text not null default 'authorized_feed',
  base_url text,
  status text default 'active',
  last_checked_at timestamptz,
  created_at timestamptz default now()
);
create table if not exists raw_listings (
  id bigint generated by default as identity primary key,
  source_key text not null,
  external_id text,
  url text,
  raw_title text,
  raw_text text,
  raw_payload jsonb,
  detected_at timestamptz default now(),
  processed boolean default false,
  unique(source_key, external_id)
);
create table if not exists normalized_listings (
  id bigint generated by default as identity primary key,
  raw_listing_id bigint references raw_listings(id) on delete cascade,
  listing_type text check (listing_type in ('room','apartment','unknown')) default 'unknown',
  district_name text,
  price numeric,
  size_mq numeric,
  room_type text,
  expenses_included boolean,
  url text,
  detected_at timestamptz default now()
);
create table if not exists listing_scores (
  id bigint generated by default as identity primary key,
  normalized_listing_id bigint references normalized_listings(id) on delete cascade,
  score numeric,
  price_score numeric,
  mobility_score numeric,
  urban_quality_score numeric,
  opportunity_score numeric,
  verdict text,
  created_at timestamptz default now()
);
create table if not exists alert_rules (
  id bigint generated by default as identity primary key,
  user_id uuid,
  listing_type text check (listing_type in ('room','apartment','any')) default 'any',
  max_budget numeric,
  districts text[],
  min_score numeric default 8,
  profile text default 'Studente',
  active boolean default true,
  created_at timestamptz default now()
);
create table if not exists alert_events (
  id bigint generated by default as identity primary key,
  alert_rule_id bigint references alert_rules(id) on delete cascade,
  normalized_listing_id bigint references normalized_listings(id) on delete cascade,
  channel text default 'email',
  status text default 'pending',
  created_at timestamptz default now(),
  sent_at timestamptz
);
create table if not exists radar_runs (
  id bigint generated by default as identity primary key,
  status text,
  records_found integer default 0,
  records_inserted integer default 0,
  started_at timestamptz default now(),
  finished_at timestamptz,
  message text
);
