-- Nesty Score Engine: benchmark giornaliero + score annunci
create table if not exists market_benchmarks (
  id bigint generated by default as identity primary key,
  district_name text not null,
  listing_type text not null check (listing_type in ('room','apartment')),
  sample_size integer default 0,
  avg_price numeric,
  median_price numeric,
  p25_price numeric,
  p75_price numeric,
  avg_euro_mq numeric,
  source text default 'normalized_listings',
  calculation_window_days integer default 30,
  calculated_at timestamptz default now(),
  unique(district_name, listing_type, calculation_window_days)
);
create table if not exists district_daily_scores (
  id bigint generated by default as identity primary key,
  district_name text not null,
  listing_type text not null check (listing_type in ('room','apartment')),
  affordability_score numeric,
  mobility_score numeric,
  urban_quality_score numeric,
  services_score numeric,
  market_depth_score numeric,
  nesty_score numeric,
  calculated_at timestamptz default now(),
  unique(district_name, listing_type)
);
create table if not exists score_engine_runs (
  id bigint generated by default as identity primary key,
  run_type text not null,
  status text not null,
  records_processed integer default 0,
  started_at timestamptz default now(),
  finished_at timestamptz,
  message text
);
create or replace view district_score_view as
select ds.district_name, ds.listing_type, ds.nesty_score, ds.affordability_score,
       ds.mobility_score, ds.urban_quality_score, ds.services_score,
       ds.market_depth_score, mb.sample_size, mb.median_price, mb.avg_price,
       mb.p25_price, mb.p75_price, mb.avg_euro_mq, ds.calculated_at
from district_daily_scores ds
left join market_benchmarks mb
  on mb.district_name = ds.district_name
 and mb.listing_type = ds.listing_type
 and mb.calculation_window_days = 30;
